sudo: false
language: python
python:
  - "3.7"
  - "3.8"
install:
  - "pip install nose coverage coveralls"
  - "pip install --editable ."
script:
  nosetests -s --with-coverage --cover-package requirements_detector --cover-inclusive
after_success:
  coveralls
