[tool.poetry]
name = "requirements-detector"
version = "1.0.0dev0"
authors = ["Landscape.io <code@landscape.io>"]
classifiers = [
    'Development Status :: 5 - Production/Stable',
    'Environment :: Console',
    'Intended Audience :: Developers',
    'Operating System :: Unix',
    'Topic :: Software Development :: Quality Assurance',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'License :: OSI Approved :: MIT License',
]
license = "MIT"
keywords = ["python","requirements detector"]
description = "Python tool to find and list requirements of a Python project"
homepage = "https://github.com/landscapeio/requirements-detector"
packages = [
  { include = "requirements_detector/"}
]
include = [
  "LICENSE",
  "README.md"
]

[tool.poetry.scripts]
prospector = 'requirements_detector.run:run'

[tool.poetry.dependencies]
python = "^3.7"
astroid = "^1.4"

[tool.poetry.dev-dependencies]
tox = "^3.24.5"
nose = "^1.3.7"
pre-commit = "^2.17.0"
coverage = "^6.3.2"
coveralls = "^3.3.1"
twine = "^3.8.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
